language: android
jdk: oraclejdk7
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  global:
    - ADB_INSTALL_TIMEOUT=10
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-16
script:
    - ./gradlew clean
    - ./gradlew test --continue
    - ./gradlew build --stacktrace