language: android
jdk: oraclejdk8

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

env:
  global:
  - MALLOC_ARENA_MAX=2
  - ADB_INSTALL_TIMEOUT=10

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-27
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-support
  - extra-android-m2repository

before_install:
- openssl aes-256-cbc -K $encrypted_85ec7c0a437d_key -iv $encrypted_85ec7c0a437d_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- yes | sdkmanager "platforms;android-27"

script:
- "./gradlew build --stacktrace"

before_deploy:
- ls -la app/
- openssl aes-256-cbc -K $encrypted_85ec7c0a437d_key -iv $encrypted_85ec7c0a437d_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- ls -la app/

deploy:
  provider: script
  script: "./gradlew app:publishApkRelease"
  skip_cleanup: true
  on:
    tags: true

# [Backup-plan] deploy to github release
#deploy:
#  provider: releases
#  api_key:
#    secure: ZxNPRLy2Q04FOuqT08D0n7U1ndyanv/8AeVONV1O2PWp3MB/8W+2llM8FeryJm/Mqhe1vxDdSmrbXCxRYs/7vSzFbYIwnffpw4IL7cIOyR4chOXObU2Jr8/0nGUJ5EosEf96gsbmFT1aYIqu9OGotEFh6wBbS5QAhtgMDwHIVXd+l06CxpNxbAyQ7P0UjXR4OPv3n6YUJqxF+nNgmEzSC54JFzcx890zjRKW44tZKgFI240S1RmPs3yys2i+P3J/h03lNk8x62AItmd+z4t0T2aHnw1C8PA5HfV9cbfafsJN8RrMxacY1KjvbxVGbL3ZqmEUoyJKbd38CQ4SiQIVu5WvOcXN8HomhVfP0UJS6KqxUbqSc0f4potGtTGbu3JMvoBePHB0YlcgspVQj3yRCBw+SJI02t+CvEcRmAcKrS23uPkxlvsxEPK8N42nSRC8oNql6ABUUUm44NmBXLn/hg1skRd333UgXdAML+aqGU8hiMbAfoscwQ4Ija2ZDIcrVjwvHdh0BQ6sPgMfWQG++O57FurDuaYIyOwXUIA+hPeCiPCYELuTRwRueyx+tjcLw24DA0AyQOSRNZQLakfuv9Nc7Pd3lZhcf8Pes7WrcFk73p+NFjaodZnyi0apFDsqezKhscKMrSqQtBQyA2PE3E9RAhSbTDyVm+AlB05i45Q=
#  file: app/build/outputs/apk/release/app-release.apk
#  skip_cleanup: true
#  on:
#    repo: tanrabad/survey
#    tags: true

notifications:
  slack:
    rooms:
      secure: L7o9sqsACG9G7VUsVBbFB8bpxS/tvzY7QtfSHVxkNEGDXyClhuQ/w33i6C4yiRFHJeYlq4LWOXRpB2mSoCBUkvCO1HKFtjofkHrwa11Ub/xJ9HmapmZq+1WXncJ63G9pi3YVxIXVLw5tSa7ehxR5S1XyxV4wq/viIfACUg4VT/L3kdD8NUhQF9Zp5uzBIxI2QXQamvBT7MNO8/bTiaVaeeLa8nVitxr6iLMUozdZieV7t3aABEUxelRgQGyHIwMM8cAVbbX3TnkSqtdNZMmZiBEKCX7apaIopk+ixncxdxyZTcSOgPtHBER9JmXEmLupBLMaGTdxohkZ5kcwVm0sGh1nBcQk4deot5Pfi4pVbF/OC+RFoXcDSskFTll3/Bi0f9e7njLHZrQgmCOFt5M5RPFdNWYYwM7h5P7qMMrhGZlI43Xxz0W/YqAHSxhODvs01VauxKpz46mRQLZ/vOlWCEekPlAjNGZBMeR0XSgcpLOuyxDk5aS0cR6HGkpISuLiPBYRMckwflK+NslWDBwUB5MDPaW6OFpf1qkwEsB6xfBYH2SZ53OYdrDd51731wq2PXBmC8Kg11Ecm3NcWgkC6xKeCiMxNSPVIhrrKIoWwIIqWlM8jrZw2tmHwseBofy1RdV2BdSYb9Hzmc0rvPqJm/IRnoSVS80k6XIkLO3uHp4=
    on_success: change
    on_failure: always
    on_start: never
