language: android
jdk: oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository
before_install:
  - openssl aes-256-cbc -K $encrypted_85ec7c0a437d_key -iv $encrypted_85ec7c0a437d_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
script:
  - ./gradlew build --stacktrace

deploy:
  provider: script
  script: ./gradlew publishApkRelease
  on:
    tags: true

notifications:
  slack:
    rooms:
      secure: L7o9sqsACG9G7VUsVBbFB8bpxS/tvzY7QtfSHVxkNEGDXyClhuQ/w33i6C4yiRFHJeYlq4LWOXRpB2mSoCBUkvCO1HKFtjofkHrwa11Ub/xJ9HmapmZq+1WXncJ63G9pi3YVxIXVLw5tSa7ehxR5S1XyxV4wq/viIfACUg4VT/L3kdD8NUhQF9Zp5uzBIxI2QXQamvBT7MNO8/bTiaVaeeLa8nVitxr6iLMUozdZieV7t3aABEUxelRgQGyHIwMM8cAVbbX3TnkSqtdNZMmZiBEKCX7apaIopk+ixncxdxyZTcSOgPtHBER9JmXEmLupBLMaGTdxohkZ5kcwVm0sGh1nBcQk4deot5Pfi4pVbF/OC+RFoXcDSskFTll3/Bi0f9e7njLHZrQgmCOFt5M5RPFdNWYYwM7h5P7qMMrhGZlI43Xxz0W/YqAHSxhODvs01VauxKpz46mRQLZ/vOlWCEekPlAjNGZBMeR0XSgcpLOuyxDk5aS0cR6HGkpISuLiPBYRMckwflK+NslWDBwUB5MDPaW6OFpf1qkwEsB6xfBYH2SZ53OYdrDd51731wq2PXBmC8Kg11Ecm3NcWgkC6xKeCiMxNSPVIhrrKIoWwIIqWlM8jrZw2tmHwseBofy1RdV2BdSYb9Hzmc0rvPqJm/IRnoSVS80k6XIkLO3uHp4=
    on_success: change
    on_failure: always
    on_start: never
